---
resources:
  - name: dinesh-concourse-git
    type: git
    source:
      uri: https://github.com/ddineesh/concourse.git
      branch: main

jobs:
  - name: job-hello-world
    public: true
    plan:
      - get: dinesh-concourse-git
      - task: hello-world
        file: dinesh-concourse-git/jobs/basic/task-hello-world/task_hello_world.yml
